baseURL = "https://blog-claudezss.vercel.app/"
languageCode = "en-us"
title = "Yan's Blogs"
theme = "itheme"

[params]

  defaultCover = 'https://www.fgdc.gov/img/slider/slider-bg-network.jpg/image' 

  [[params.socialMedia]] 
    name = 'Github'
    url = 'https://github.com/claudezss'
